repos:
  - repo: local
    hooks:
      - id: Remove jupyter running result
        name: Remove jupyter running result
        entry: jupyter
        language: system
        files: '[examples|ready]/.*\.ipynb'
        args: [
          "nbconvert",
          "--ClearOutputPreprocessor.enabled=True",
          "--ClearMetadataPreprocessor.enabled=True",
          "--clear-output",
          "--inplace",
        ]
        require_serial: false
        additional_dependencies: [ ]
        minimum_pre_commit_version: '0'
      - id: Remove jupyter metadata and empty cell
        name: Remove jupyter metadata and empty cell
        entry: jupyter
        language: system
        files: '.*\.ipynb'
        args: [
          "nbconvert",
          --ClearMetadataPreprocessor.enabled=True,
          --RegexRemovePreprocessor.enabled=True,
          --RegexRemovePreprocessor.patterns,
          "\\s*\\Z",
          --inplace,
        ]
        require_serial: false
        additional_dependencies: [ ]
        minimum_pre_commit_version: '0'